name: Nix environment

on:
  push:
    paths:
      - flake.nix
      - shell.nix
      - flake.lock
    branches:
      - master
  pull_request:
    paths:
      - flake.nix
      - shell.nix
      - flake.lock
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: saber
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check flake
        run: nix flake check -v --show-trace --no-update-lock-file
      - run: nix build .#ci
      - run: nix develop -c echo success
